<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Traditional Punjabi Suit',
                'slug' => 'traditional-punjabi-suit',
                'sku' => 'PUNJ-001',
                'short_description' => 'Elegant and comfortable traditional Punjabi suit',
                'description' => 'Beautiful traditional Punjabi suit made with premium fabric. Perfect for weddings, festivals, and special occasions. Features intricate embroidery and comfortable fit.',
                'price' => 2499.00,
                'sale_price' => 1999.00,
                'cost_price' => 1200.00,
                'image' => '/images/products/punjabi-suit-1.jpg',
                'gallery' => [
                    '/images/products/punjabi-suit-1-1.jpg',
                    '/images/products/punjabi-suit-1-2.jpg',
                ],
                'stock_quantity' => 50,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'low_stock_threshold' => 10,
                'category' => "Women's Wear",
                'subcategory' => 'Punjabi Suits',
                'brand' => 'Ecomarc',
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['Red', 'Blue', 'Green', 'Pink', 'Yellow'],
                'attributes' => [
                    'material' => 'Cotton',
                    'pattern' => 'Embroidered',
                    'occasion' => 'Wedding, Festival',
                ],
                'weight' => 0.5,
                'status' => 'published',
                'featured' => true,
                'is_active' => true,
                'meta_title' => 'Traditional Punjabi Suit - Ecomarc Punjabi Shop',
                'meta_description' => 'Buy elegant traditional Punjabi suits online. Premium quality fabric with beautiful embroidery.',
                'meta_keywords' => 'punjabi suit, traditional wear, women clothing, indian dress',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Designer Patiala Suit',
                'slug' => 'designer-patiala-suit',
                'sku' => 'PUNJ-002',
                'short_description' => 'Stylish and modern Punjabi attire',
                'description' => 'Contemporary Patiala suit with modern design elements. Comfortable and stylish, perfect for daily wear and casual occasions.',
                'price' => 3999.00,
                'sale_price' => null,
                'cost_price' => 2000.00,
                'image' => '/images/products/patiala-suit-1.jpg',
                'gallery' => [
                    '/images/products/patiala-suit-1-1.jpg',
                    '/images/products/patiala-suit-1-2.jpg',
                ],
                'stock_quantity' => 30,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'low_stock_threshold' => 10,
                'category' => "Women's Wear",
                'subcategory' => 'Patiala Suits',
                'brand' => 'Ecomarc',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Navy Blue', 'Maroon', 'Purple', 'Black'],
                'attributes' => [
                    'material' => 'Georgette',
                    'pattern' => 'Printed',
                    'occasion' => 'Casual, Party',
                ],
                'weight' => 0.6,
                'status' => 'published',
                'featured' => true,
                'is_active' => true,
                'meta_title' => 'Designer Patiala Suit - Ecomarc Punjabi Shop',
                'meta_description' => 'Buy designer Patiala suits online. Modern designs with comfortable fit.',
                'meta_keywords' => 'patiala suit, designer wear, punjabi dress, women clothing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Punjabi Dupatta',
                'slug' => 'punjabi-dupatta',
                'sku' => 'PUNJ-003',
                'short_description' => 'Beautiful handcrafted dupatta',
                'description' => 'Elegant Punjabi dupatta with intricate work. Perfect complement to your Punjabi suit collection.',
                'price' => 899.00,
                'sale_price' => 699.00,
                'cost_price' => 400.00,
                'image' => '/images/products/dupatta-1.jpg',
                'gallery' => [
                    '/images/products/dupatta-1-1.jpg',
                ],
                'stock_quantity' => 100,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'low_stock_threshold' => 20,
                'category' => 'Accessories',
                'subcategory' => 'Dupattas',
                'brand' => 'Ecomarc',
                'sizes' => ['One Size'],
                'colors' => ['Red', 'Blue', 'Green', 'Pink', 'Yellow', 'Orange'],
                'attributes' => [
                    'material' => 'Chiffon',
                    'pattern' => 'Embroidered',
                    'length' => '2.5 meters',
                ],
                'weight' => 0.2,
                'status' => 'published',
                'featured' => false,
                'is_active' => true,
                'meta_title' => 'Punjabi Dupatta - Ecomarc Punjabi Shop',
                'meta_description' => 'Buy beautiful Punjabi dupattas online. Handcrafted with premium materials.',
                'meta_keywords' => 'dupatta, punjabi dupatta, scarf, women accessory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Men's Kurta Pajama",
                'slug' => 'mens-kurta-pajama',
                'sku' => 'PUNJ-004',
                'short_description' => 'Comfortable traditional menswear',
                'description' => 'Classic men\'s kurta pajama set. Comfortable cotton fabric perfect for daily wear and special occasions.',
                'price' => 1999.00,
                'sale_price' => null,
                'cost_price' => 1000.00,
                'image' => '/images/products/kurta-pajama-1.jpg',
                'gallery' => [
                    '/images/products/kurta-pajama-1-1.jpg',
                    '/images/products/kurta-pajama-1-2.jpg',
                ],
                'stock_quantity' => 40,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'low_stock_threshold' => 10,
                'category' => "Men's Wear",
                'subcategory' => 'Kurta Pajama',
                'brand' => 'Ecomarc',
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['White', 'Beige', 'Light Blue', 'Grey'],
                'attributes' => [
                    'material' => 'Cotton',
                    'pattern' => 'Solid',
                    'occasion' => 'Casual, Formal',
                ],
                'weight' => 0.7,
                'status' => 'published',
                'featured' => true,
                'is_active' => true,
                'meta_title' => "Men's Kurta Pajama - Ecomarc Punjabi Shop",
                'meta_description' => 'Buy comfortable men\'s kurta pajama online. Premium quality cotton fabric.',
                'meta_keywords' => 'kurta pajama, mens wear, traditional wear, indian clothing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kids Punjabi Suit',
                'slug' => 'kids-punjabi-suit',
                'sku' => 'PUNJ-005',
                'short_description' => 'Adorable Punjabi suit for kids',
                'description' => 'Cute and comfortable Punjabi suit for kids. Made with soft, skin-friendly fabric.',
                'price' => 1299.00,
                'sale_price' => 999.00,
                'cost_price' => 600.00,
                'image' => '/images/products/kids-suit-1.jpg',
                'gallery' => [
                    '/images/products/kids-suit-1-1.jpg',
                ],
                'stock_quantity' => 25,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'low_stock_threshold' => 5,
                'category' => "Kids Wear",
                'subcategory' => 'Punjabi Suits',
                'brand' => 'Ecomarc',
                'sizes' => ['2-3 Years', '4-5 Years', '6-7 Years', '8-9 Years'],
                'colors' => ['Pink', 'Blue', 'Red', 'Yellow'],
                'attributes' => [
                    'material' => 'Cotton',
                    'pattern' => 'Printed',
                    'age_group' => '2-9 Years',
                ],
                'weight' => 0.3,
                'status' => 'published',
                'featured' => false,
                'is_active' => true,
                'meta_title' => 'Kids Punjabi Suit - Ecomarc Punjabi Shop',
                'meta_description' => 'Buy cute kids Punjabi suits online. Comfortable and stylish.',
                'meta_keywords' => 'kids punjabi suit, children wear, kids clothing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Product::insert($products);
    }
}
